### ISSUE TITLE
Building wheel on OSX 10.15 and Python 3.7 fails

### ISSUE THREAD

**Issue by KimiNewt** [bloomberg/memray#193]
## Bug Report

**Current Behavior** 

Attempting to build wheel with `bdist_wheel` fails:

```
discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.


!!

  check.warn(importable)
/private/var/folders/y5/75r42cfx59sd7607107c1htc0000gn/T/pip-build-env-kvr2zjc8/overlay/lib/python3.7/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'memray.reporters.templates.assets' as data is deprecated, please list it in `packages`.
    !!


    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'memray.reporters.templates.assets' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'memray.reporters.templates.assets' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'memray.reporters.templates.assets' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.


!!

  check.warn(importable)
error: command '/usr/bin/clang' failed with exit code 1
----------------------------------------
Failed building wheel for memray
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_aviv/da2ad95f2a4a85916beda35c129408b1/execroot/armis/bazel-out/darwin-opt/bin/thirdparty/pip/lock.runfiles/com_apt_itude_rules_pip/src/bin/lock_pip_requirements.py", line 145, in <module>
    main()
  File "/private/var/tmp/_bazel_aviv/da2ad95f2a4a85916beda35c129408b1/execroot/armis/bazel-out/darwin-opt/bin/thirdparty/pip/lock.runfiles/com_apt_itude_rules_pip/src/bin/lock_pip_requirements.py", line 41, in main
    wheel_directory,
  File "/private/var/tmp/_bazel_aviv/da2ad95f2a4a85916beda35c129408b1/execroot/armis/bazel-out/darwin-opt/bin/thirdparty/pip/lock.runfiles/com_apt_itude_rules_pip/src/piprules/resolve.py", line 26, in resolve_requirement_set
    return resolver.resolve(requirement_list)
  File "/private/var/tmp/_bazel_aviv/da2ad95f2a4a85916beda35c129408b1/execroot/armis/bazel-out/darwin-opt/bin/thirdparty/pip/lock.runfiles/com_apt_itude_rules_pip/src/piprules/resolve.py", line 148, in resolve
    built_wheels = self._build_wheels_if_necessary(requirements)
  File "/private/var/tmp/_bazel_aviv/da2ad95f2a4a85916beda35c129408b1/execroot/armis/bazel-out/darwin-opt/bin/thirdparty/pip/lock.runfiles/com_apt_itude_rules_pip/src/piprules/resolve.py", line 171, in _build_wheels_if_necessary
    raise WheelBuildError(build_failures)
piprules.resolve.WheelBuildError: Failed to build one or more wheels
```
I see that there's a wheel on pypi for 3.8+ but the package is supposed to be supported in 3.7 as well.

**Expected behavior/code** A built wheel :)

**Environment**

Mac OSX 10.15 

- Python(s): Python 3.7.3

**Comment by pablogsal** [comment]
@KimiNewt thanks for submitting the issue.

Notice that we only support macOS >= 11 because that's what we test against. You may need to set the `MACOS_DEPLOYMENT_TARGET` to 11.

Unfortunately I don't see the error messages from clang in your output. Could you try again in verbose mode and attach the compilation errors so we can better see what's failing? It may be very likely that you are missing some of the dependencies (see the "build from source" section in the README).

**Comment by KimiNewt** [comment]
Upon further inspection you are correct. This was a local error and I've resolved it. Sorry for the trouble and thanks for this amazing project :)
