### ISSUE TITLE
Fatal Python error: PyThreadState_Get: the function must be called with the GIL held

### ISSUE THREAD

**Issue by pramodk** [bloomberg/memray#227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to run a Python application with C/C++ library/module then I get:

```console
Fatal Python error: PyThreadState_Get: the function must be called with the GIL held, but the GIL is released (the current Python thread state is NULL)
Python runtime state: finalizing (tstate=0x40b790)

Aborted
```

### Expected Behavior

Application should finishes without an error

### Steps To Reproduce

1. Install required packages:

```console
python3 -m venv env
env/bin/activate
pip install neuron memray
```

2. Create a simple example that just imports neuron package and quit the program:

```python
$ cat test2.py
from neuron import h
h.quit()
```

3. Running it gives:

```console
$ memray run -f -o output.bin test.py
Writing profile results into output.bin
Memray WARNING: Correcting symbol for aligned_alloc from 0x7fffe5b09ab0 to 0x7fffec68e000
Warning: no DISPLAY environment variable.
--No graphics will be displayed.
-65.0
Fatal Python error: PyThreadState_Get: the function must be called with the GIL held, but the GIL is released (the current Python thread state is NULL)
Python runtime state: finalizing (tstate=0x40b790)

Aborted
```

### Memray Version

1.3.1

### Python Version

3.9

### Operative System

Linux

### Anything else?

This is with [neuron](https://github.com/neuronsimulator/nrn) simulator used in the neuroscience community. I briefly experimented with different things and see that if I avoid `h.quit()` then I don't see this error. I could take a look at the implementation but I would be curious to know why this "conflicts" with memray.  I haven't seen such errors with other profilers we typically use.

And finally, thanks for an excellent tool! ❤️

**Comment by pablogsal** [comment]
Hi @pramodk and thanks a lot for opening this issue. I'm sorry you encountered this problem with `memray`.

Seems that the way `h.quit()` stops the program in a peculiar way and `memray` currently expects normal program termination. In particular, from what I can see, it seems that `h.quit()` conflicts with `memray` because it releases the GIL and then quits the program:

https://github.com/neuronsimulator/nrn/blob/67f9bd250ce1ca086fbe3ba177d4864b9192ef52/src/oc/hoc.cpp#L1027-L1042

and 

https://github.com/neuronsimulator/nrn/blob/b46b452361728c0834f33b86c13449d6d40e50df/src/nrnpython/inithoc.cpp#L220-L232

Apparently, this early termination causes the interpreter to be finished but the `memray` tracker is still alive. It seems that we can handle this better in `memray` by installing an `atexit` handler that destroys any `memray` tracker before the Python interpreter is finished. The other alternative is checking if we are finalizing the interpreter an bailing out some of the destructor calls. Maybe both.

We will try to make a PR fixing this soon. Thanks again for raising the issue!

**Comment by pablogsal** [comment]
Backtrace of the crash for completion:

```
hread 1 "python" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44            return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff7d0d6b3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff7cbd958 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7ca753d in __GI_abort () at abort.c:79
#4  0x000055555563c8da in fatal_error_exit (status=-1) at Python/pylifecycle.c:2553
#5  fatal_error (fd=<optimized out>, header=header@entry=1, prefix=prefix@entry=0x555555830e10 <__func__.6.lto_priv.3> "PyThreadState_Get",
    msg=msg@entry=0x5555557e19f8 "the function must be called with the GIL held, but the GIL is released (the current Python thread state is NULL)", status=status@entry=-1) at Python/pylifecycle.c:2664
#6  0x000055555563cc8c in _Py_FatalErrorFunc (func=func@entry=0x555555830e10 <__func__.6.lto_priv.3> "PyThreadState_Get",
    msg=msg@entry=0x5555557e19f8 "the function must be called with the GIL held, but the GIL is released (the current Python thread state is NULL)") at Python/pylifecycle.c:2750
#7  0x000055555563ccd5 in _Py_FatalError_TstateNULL (func=func@entry=0x555555830e10 <__func__.6.lto_priv.3> "PyThreadState_Get")
    at Python/ceval.c:271
#8  0x00005555555b42e5 in _Py_EnsureFuncTstateNotNULL (tstate=<optimized out>, func=<synthetic pointer>)
    at ./Include/internal/pycore_pystate.h:95
#9  PyThreadState_Get () at Python/pystate.c:1015
#10 0x00007ffff75be9ca in memray::compat::setprofileAllThreads (arg=0x0, func=0x0) at src/memray/_memray/compat.cpp:6
#11 memray::tracking_api::PythonStackTracker::removeProfileHooks () at src/memray/_memray/tracking_api.cpp:493
#12 memray::tracking_api::Tracker::~Tracker (this=<optimized out>, this=<optimized out>) at src/memray/_memray/tracking_api.cpp:568
#13 0x00007ffff75c11b1 in std::default_delete<memray::tracking_api::Tracker>::operator() (__ptr=0x555555abdee0, this=<optimized out>)
    at /usr/include/c++/12.2.0/bits/unique_ptr.h:95
#14 std::unique_ptr<memray::tracking_api::Tracker, std::default_delete<memray::tracking_api::Tracker> >::~unique_ptr (this=<optimized out>,
    this=<optimized out>) at /usr/include/c++/12.2.0/bits/unique_ptr.h:396
#15 0x00007ffff7cbffa5 in __run_exit_handlers (status=0, listp=0x7ffff7e5d760 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true,
    run_dtors=run_dtors@entry=true) at exit.c:113
#16 0x00007ffff7cc0120 in __GI_exit (status=<optimized out>) at exit.c:143
#17 0x00007ffff58fde11 in hoc_quit() ()
   from /home/pablogsal/.pyenv/versions/3.10.1/envs/memray/lib/python3.10/site-packages/neuron/.data/lib/libnrniv.so
#18 0x00007ffff58f7a04 in hoc_call() ()
   from /home/pablogsal/.pyenv/versions/3.10.1/envs/memray/lib/python3.10/site-packages/neuron/.data/lib/libnrniv.so
#19 0x00007ffff694cd32 in fcall(void*, void*) ()
   from /home/pablogsal/.pyenv/versions/3.10.1/envs/memray/lib/python3.10/site-packages/neuron/.data/lib/libnrnpython3.so
#20 0x00007ffff58b5862 in OcJumpImpl::fpycall(void* (*)(void*, void*), void*, void*) ()
   from /home/pablogsal/.pyenv/versions/3.10.1/envs/memray/lib/python3.10/site-packages/neuron/.data/lib/libnrniv.so
#21 0x00007ffff694705c in hocobj_call(PyHocObject*, _object*, _object*) ()
   from /home/pablogsal/.pyenv/versions/3.10.1/envs/memray/lib/python3.10/site-packages/neuron/.data/lib/libnrnpython3.so
#22 0x0000555555693d03 in _PyObject_MakeTpCall (tstate=0x5555558f7d80, callable=<hoc.HocObject at remote 0x7ffff6a88210>, args=<optimized out>,
    nargs=<optimized out>, keywords=0x0) at Objects/call.c:215
#23 0x0000555555690404 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7fffffffba80,
    tstate=<optimized out>) at Python/ceval.c:5893
#24 _PyEval_EvalFrameDefault (tstate=<optimized out>, Python Exception <class 'gdb.error'>: There is no member named f_frame.
f=, throwflag=<optimized out>) at Python/ceval.c:4197
#25 0x000055555573b032 in _PyEval_EvalFrame (throwflag=0, Python Exception <class 'gdb.error'>: There is no member named f_frame.
f=, tstate=0x5555558f7d80) at ./Include/internal/pycore_ceval.h:46
#26 _PyEval_Vector (tstate=0x5555558f7d80, con=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>,
    kwnames=<optimized out>) at Python/ceval.c:5081
,,,
```

and this is the Python backtrace:

```
Traceback (most recent call first):
  File "lel.py", line 8, in <module>
    h.quit()
  <built-in method exec of module object at remote 0x7ffff7c18590>
  File "/home/pablogsal/.pyenv/versions/3.10.1/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/pablogsal/.pyenv/versions/3.10.1/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/pablogsal/.pyenv/versions/3.10.1/lib/python3.10/runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/pablogsal/github/memray/src/memray/commands/run.py", line 63, in _run_tracker
    runpy.run_path(args.script, run_name="__main__")
  File "/home/pablogsal/github/memray/src/memray/commands/run.py", line 167, in _run_with_file_output
    _run_tracker(
  File "/home/pablogsal/github/memray/src/memray/commands/run.py", line 312, in run
    _run_with_file_output(args)
  File "/home/pablogsal/github/memray/src/memray/commands/__init__.py", line 126, in main
    arg_values.entrypoint(arg_values, parser)
  File "/home/pablogsal/github/memray/src/memray/__main__.py", line 6, in <module>
    sys.exit(main())
  <built-in method exec of module object at remote 0x7ffff7c18590>
  File "/home/pablogsal/.pyenv/versions/3.10.1/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/pablogsal/.pyenv/versions/3.10.1/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
```
