### ISSUE TITLE
Receiving segmentation error

### ISSUE THREAD

**Issue by sethmlarson** [bloomberg/memray#288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running pytest-memray with coverage in urllib3, occasionally seeing segmentation errors ([ref](https://github.com/urllib3/urllib3/actions/runs/3877342346/jobs/6612256458)):

```
Fatal Python error: Segmentation fault

Thread 0x00007fe6c2ffe700 (most recent call first):
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/selectors.py", line 468 in select
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/asyncio/base_events.py", line 1823 in _run_once
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/asyncio/base_events.py", line 570 in run_forever
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/asyncio/base_events.py", line 603 in run_until_complete
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/asyncio/runners.py", line 44 in run
  File "/home/runner/work/urllib3/urllib3/dummyserver/server.py", line 241 in _run_and_close_tornado
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/concurrent/futures/thread.py", line 57 in run
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/concurrent/futures/thread.py", line 80 in _worker
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/threading.py", line 870 in run
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007fe6c95e7700 (most recent call first):
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/ssl.py", line 1101 in read
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/ssl.py", line 1226 in recv
  File "/home/runner/work/urllib3/urllib3/dummyserver/testcase.py", line 31 in consume_socket
  File "/home/runner/work/urllib3/urllib3/test/test_ssltransport.py", line 121 in socket_handler
  File "/home/runner/work/urllib3/urllib3/dummyserver/server.py", line 145 in _start_server
  File "/home/runner/work/urllib3/urllib3/dummyserver/server.py", line 149 in run
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fe6cfe10740 (most recent call first):
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/pytest_memray/plugin.py", line 125 in wrapper
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/_pytest/python.py", line 195 in pytest_pyfunc_call
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/_pytest/python.py", line 1789 in runtest
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/_pytest/runner.py", line 167 in pytest_runtest_call
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/_pytest/runner.py", line 260 in <lambda>
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/_pytest/runner.py", line 339 in from_call
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/_pytest/runner.py", line 259 in call_runtest_hook
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/flaky/flaky_pytest_plugin.py", line 138 in call_and_report
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/_pytest/runner.py", line 131 in runtestprotocol
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/_pytest/runner.py", line 112 in pytest_runtest_protocol
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/flaky/flaky_pytest_plugin.py", line 94 in pytest_runtest_protocol
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/_pytest/main.py", line 349 in pytest_runtestloop
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/_pytest/main.py", line 324 in _main
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/_pytest/main.py", line 270 in wrap_session
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/_pytest/main.py", line 317 in pytest_cmdline_main
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/_pytest/config/__init__.py", line 167 in main
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/_pytest/config/__init__.py", line 190 in console_main
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/pytest/__main__.py", line 5 in <module>
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/coverage/execfile.py", line 199 in run
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/coverage/cmdline.py", line 830 in do_run
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/coverage/cmdline.py", line 659 in command_line
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/coverage/cmdline.py", line 943 in main
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/coverage/__main__.py", line 8 in <module>
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/runpy.py", line 87 in _run_code
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/runpy.py", line 194 in _run_module_as_main
```

Not sure why this is happening, toughest part is it's a very rare occurrence as most jobs are passing just fine.

### Expected Behavior

No crash

### Steps To Reproduce

- Install memray, pytest-memray, coverage
- Run `coverage python -m pytest ...` on the urllib3 test suite
- Sometimes crash with segfault? :(

### Memray Version

1.5.0

### Python Version

3.8

### Operative System

Linux

### Anything else?

Let us know if there's something we can do to make capturing a better reproducer for this issue.

**Comment by godlygeek** [comment]
> * Sometimes crash with segfault? :(

😢

> Let us know if there's something we can do to make capturing a better reproducer for this issue.

Well, I'm trying to reproduce it in an Ubuntu 20.04 Docker container, but I haven't had any luck so far running the test suite in a loop. You say that you're occasionally seeing segfaults - do you have a feel for how often they occur?

Based on the Python stack that `faulthandler` captured, the segfault happened in the file reader. That doesn't surprise me; the reader is generally trusting of the file written by the writer, and invalid files can crash the reader as things stand today.

This probably means that the writer has done something wrong and somehow written an invalid capture file, and the reader is choking on it. The fact that you've got several threads running at the point where the file is being read makes me suspicious - there's some tricky work involved in capturing the stacks of threads that already existed at the point where Memray tracking started, so it's possible that our bug is somewhere around there, but that's just a hunch so far.

Unfortunately, until we see a core file or native stack trace, or even a copy of the memray results file, we're really shooting in the dark.

I've found https://github.com/lhotari/action-upterm to be extremely useful for tracking down issues that are occurring in a GitHub Actions context - it spawns an upterm session that you can connect to, allowing you ssh access to the container before or after the tests run. If this is failing 1 out of 5 times, maybe that's a way for us to grab a core file or the results file when it fails, or to run the test suite under `gdb` to get a backtrace and allow live inspection. But if it's failing 1 out of 1000 times, that's probably not super helpful, since it does require some manual interaction.

**Comment by pablogsal** [comment]
I left my computer tunning `python3 -bb -m coverage run --parallel-mode -m pytest --memray --hide-memray-summary -v -ra --color=yes --tb=native --no-success-flaky-report --durations=10 --strict-config --strict-markers test/  -vvvv` all night in a loop in a docker container with `ubuntu:20.04` running Python 3.8 and unfortunately I haven't been able to reproduce it :(

As @godlygeek mentions, we are going to need either a core file, a native stack trace or the memray dump file that's making it crash so we can make progress.

**Comment by pablogsal** [comment]
I also executed the whole `urllib3` test suite under `valgrind` and `helgrind` (which took a lot of time) independently and neither reported any errors :(

The command for `valgrind` (the `../valgrind.supp ` is in the `memray ` root): 
```
PYTHONMALLOC=malloc valgrind \
        --suppressions=../valgrind.supp \
        --leak-check=full \
        --show-leak-kinds=definite \
        --error-exitcode=1 \
        --gen-suppressions=all python3 -bb -m coverage run --parallel-mode -m pytest --memray --hide-memray-summary -v -ra --color=yes --tb=native --no-success-flaky-report --durations=10 --strict-config --strict-markers test/  -vvvv
```

The command for `helgrind` (the `../valgrind.supp ` is in the `memray ` root): 

```
PYTHONMALLOC=malloc valgrind  \
        --suppressions=../valgrind.supp \
        --tool=helgrind \
        --error-exitcode=1 \
        --gen-suppressions=all python3 -bb -m coverage run --parallel-mode -m pytest --memray --hide-memray-summary -v -ra --color=yes --tb=native --no-success-flaky-report --durations=10 --strict-config --strict-markers test/  -vvvv
```

**Comment by pquentin** [comment]
Thank you both for trying! We'll try to provide that data to you, but it could take days/weeks. Would you prefer closing the issues in the meantime?

**Comment by pablogsal** [comment]
> Thank you both for trying! We'll try to provide that data to you, but it could take days/weeks

Thanks a lot! We will wait for the data! Not sure what will be easier to obtain, but just in case you can prioritise, this is the order of usefulness: 

1. The results file (this is [created by pytest-memray automatically in a temporary directory](https://github.com/bloomberg/pytest-memray/blob/38195a67969a62d31c817afaf84222ef831c3bba/src/pytest_memray/plugin.py#L137-L147)).
2. A core file for the crash
3. A native stack trace (with C functions and locations).

> Would you prefer closing the issues in the meantime?

We will discuss this today. Maybe we could add some kind of code that can print some information before crashing, but I am not sure if that's possible without slowing down things.

**Comment by pablogsal** [comment]
@pquentin @sethmlarson  One cheap way to get a stack trace on segfault:

With the following code C:

```C
#define __USE_GNU
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <execinfo.h>
#include <unistd.h>
#include <string.h>

void segfault_handler(int signal, siginfo_t* siginfo, void* context) {
  void *array[1000];
  size_t size;

  size = backtrace(array, 1000);
  fprintf(stderr, "Error: signal %d:\n", signal);
  backtrace_symbols_fd(array, size, STDERR_FILENO);
  exit(1);
}

__attribute__((constructor))
void install_sigsegv() {
  struct sigaction sig;
  sig.sa_sigaction = segfault_handler;
  sig.sa_flags = SA_SIGINFO;

  if(sigaction(SIGSEGV, &sig, NULL) < 0) {
    puts("[error] signal registering failed");
    exit(-1);
  }
}
```

Compile as `gcc the_file.c -o segfaulter.so --shared -fpic` and you can run any program with `LD_PRELOAD=PATH_TO_SEGFAULTER.SO` and will print the native trace on segfault

For example usage:

```
root@98e633069c53:/# LD_PRELOAD=./segfaulter.so python3 -c 'import signal;import os; os.kill(os.getpid(), signal.SIGSEGV)'
Error: signal 11:
./segfaulter.so(segfault_handler+0x3c)[0xffffa8b70b4c]
linux-vdso.so.1(__kernel_rt_sigreturn+0x0)[0xffffa8bc6790]
/lib/aarch64-linux-gnu/libc.so.6(kill+0xc)[0xffffa88ea8cc]
python3(+0x23e460)[0xaaaac573e460]
python3(+0x10452c)[0xaaaac560452c]
python3(_PyEval_EvalFrameDefault+0x4c10)[0xaaaac55f0bf0]
python3(+0x1e9a80)[0xaaaac56e9a80]
python3(PyEval_EvalCode+0x74)[0xaaaac56e9904]
python3(+0x21f1ec)[0xaaaac571f1ec]
python3(+0x2168d8)[0xaaaac57168d8]
python3(PyRun_StringFlags+0x84)[0xaaaac570e058]
python3(PyRun_SimpleStringFlags+0x40)[0xaaaac570ded4]
python3(Py_RunMain+0x31c)[0xaaaac570cacc]
python3(Py_BytesMain+0x24)[0xaaaac56dab08]
/lib/aarch64-linux-gnu/libc.so.6(+0x273fc)[0xffffa88d73fc]
/lib/aarch64-linux-gnu/libc.so.6(__libc_start_main+0x98)[0xffffa88d74cc]
python3(_start+0x30)[0xaaaac56da9f0]
```

**Comment by pablogsal** [comment]
@pquentin @sethmlarson Good news, by the usage of arcane rituals and **a LOT of time** (i spent my workday on this), I was able to reproduce it once and I have a stack trace:

```
(gdb) info threads
  Id   Target Id                         Frame
  1    Thread 0x7f5270804700 (LWP 50462) __GI_raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:50
* 2    Thread 0x7f52774cf740 (LWP 50298) 0x00007f527575da54 in std::istream::sentry::sentry(std::istream&, bool) () from /lib/x86_64-linux-gnu/libstdc++.so.6
```


This is the stack
```
Thread 2 (Thread 0x7f52774cf740 (LWP 50298)):
#0  0x00007f527575da54 in std::istream::sentry::sentry(std::istream&, bool) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007f527575ea5f in std::istream::read(char*, long) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007f5275c81e55 in memray::io::FileSource::read(char*, long) () from /usr/local/lib/python3.8/dist-packages/memray/_memray.cpython-38-x86_64-linux-gnu.so
#3  0x00007f5275c9addb in memray::api::RecordReader::nextRecord() () from /usr/local/lib/python3.8/dist-packages/memray/_memray.cpython-38-x86_64-linux-gnu.so
#4  0x00007f5275cbb6ec in __pyx_pf_6memray_7_memray_10FileReader___cinit__(__pyx_obj_6memray_7_memray_FileReader*, _object*, bool) [clone .lto_priv.457] () from /usr/local/lib/python3.8/dist-packages/memray/_memray.cpython-38-x86_64-linux-gnu.so
#5  0x00007f5275caa9b9 in __pyx_tp_new_6memray_7_memray_FileReader(_typeobject*, _object*, _object*) () from /usr/local/lib/python3.8/dist-packages/memray/_memray.cpython-38-x86_64-linux-gnu.so
#6  0x00000000005f65f3 in ?? ()
#7  0x00000000000007a8 in ?? ()
#8  0x00000000005a6c10 in ?? ()
#9  0x00007f5275fce880 in ?? ()
#10 0x0000000001f98840 in ?? ()
#11 0x00007f5275fce89e in ?? ()
#12 0x0000000001f98a00 in ?? ()
#13 0x00000000015fbba0 in ?? ()
#14 0x0000000001f989f0 in ?? ()
#15 0x00007f5275ef8fc0 in ?? ()
#16 0x0000000000572dea in ?? ()
#17 0x00007f5275fce870 in ?? ()
#18 0x0000000001f989a8 in ?? ()
#19 0x00007f5275f65ba0 in ?? ()
#20 0x00007f5275f85610 in ?? ()
#21 0x00007f5275f9da80 in ?? ()
#22 0x0000000000000000 in ?? ()

Thread 1 (Thread 0x7f5270804700 (LWP 50462)):
#0  __GI_raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  <signal handler called>
#2  __GI___pthread_mutex_lock (mutex=0x10) at ../nptl/pthread_mutex_lock.c:67
#3  0x00007f5275c8887f in memray::tracking_api::Tracker::trackAllocationImpl(void*, unsigned long, memray::hooks::Allocator) () from /usr/local/lib/python3.8/dist-packages/memray/_memray.cpython-38-x86_64-linux-gnu.so
#4  0x00007f5275ca0723 in memray::intercept::malloc(unsigned long) () from /usr/local/lib/python3.8/dist-packages/memray/_memray.cpython-38-x86_64-linux-gnu.so
#5  0x00007f527704bc0e in CRYPTO_zalloc () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#6  0x00007f5276f6db41 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#7  0x00007f5276f6b3f3 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#8  0x00007f5276f6bf82 in ASN1_item_ex_d2i () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#9  0x00007f5276f6c00f in ASN1_item_d2i () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#10 0x00007f52763cefbf in d2i_SSL_SESSION () from /lib/x86_64-linux-gnu/libssl.so.1.1
#11 0x00007f52763fc1e2 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#12 0x00007f52763ee58f in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#13 0x00007f52763d9d98 in SSL_do_handshake () from /lib/x86_64-linux-gnu/libssl.so.1.1
#14 0x00007f527644a04c in ?? () from /usr/lib/python3.8/lib-dynload/_ssl.cpython-38-x86_64-linux-gnu.so
#15 0x00000000005c43c6 in ?? ()
#16 0x00007f5271b67d60 in ?? ()
#17 0x0000000000575298 in ?? ()
#18 0x00007f5271b67ee8 in ?? ()
#19 0x000000000068dc54 in ?? ()
#20 0x00007f5276393430 in ?? ()
#21 0x0000000000000000 in ?? ()
```

This is the disasembly around the crash:

```
   0x00007f5275c88821 <+529>:   callq  0x7f5275c6f250 <_ZdlPv@plt>
   0x00007f5275c88826 <+534>:   jmpq   0x7f5275c889c4 <_ZN6memray12tracking_api7Tracker19trackAllocationImplEPvmNS_5hooks9AllocatorE+948>
   0x00007f5275c8882b <+539>:   nopl   0x0(%rax,%rax,1)
   0x00007f5275c88830 <+544>:   mov    (%rsp),%rax
   0x00007f5275c88834 <+548>:   mov    0x78(%rbp),%rbx
   0x00007f5275c88838 <+552>:   mov    %rax,0xb0(%rsp)
   0x00007f5275c88840 <+560>:   mov    0x8(%rsp),%rax
   0x00007f5275c88845 <+565>:   mov    %rax,0xb8(%rsp)
   0x00007f5275c8884d <+573>:   movzbl 0x18(%rsp),%eax
   0x00007f5275c88852 <+578>:   mov    %al,0xc0(%rsp)
   0x00007f5275c88859 <+585>:   callq  0x7f5275c6eff0 <_ZTHN6memray12tracking_api5t_tidE@plt>
   0x00007f5275c8885e <+590>:   mov    0x2695e3(%rip),%rax        # 0x7f5275ef1e48
   0x00007f5275c88865 <+597>:   cmpq   $0x0,0x269723(%rip)        # 0x7f5275ef1f90
   0x00007f5275c8886d <+605>:   lea    0x10(%rbx),%rbp
   0x00007f5275c88871 <+609>:   mov    %fs:(%rax),%r12
   0x00007f5275c88875 <+613>:   je     0x7f5275c88887 <_ZN6memray12tracking_api7Tracker19trackAllocationImplEPvmNS_5hooks9AllocatorE+631>
   0x00007f5275c88877 <+615>:   mov    %rbp,%rdi
   0x00007f5275c8887a <+618>:   callq  0x7f5275c70d20 <pthread_mutex_lock@plt>
=> 0x00007f5275c8887f <+623>:   test   %eax,%eax
   0x00007f5275c88881 <+625>:   jne    0x7f5275c88dcd <_ZN6memray12tracking_api7Tracker19trackAllocationImplEPvmNS_5hooks9AllocatorE+1981>
   0x00007f5275c88887 <+631>:   mov    0x8(%rbx),%rdi
   0x00007f5275c8888b <+635>:   cmp    0xb0(%rbx),%r12
   0x00007f5275c88892 <+642>:   je     0x7f5275c88d60 <_ZN6memray12tracking_api7Tracker19trackAllocationImplEPvmNS_5hooks9AllocatorE+1872>
```

**Comment by pablogsal** [comment]
Ok, this was very annoying to fix, but we think we got it in #289. We will do a release soon 👍

**Comment by pablogsal** [comment]
Thanks a lot for the report btw, and sorry for the trouble!

**Comment by sethmlarson** [comment]
@pablogsal It's no trouble at all, thank you so much for this package and the quick turnaround. We know that sort of thing doesn't come free! 🙇

**Comment by pablogsal** [comment]
We released a new version with the fix yesterday.

Let us know if you experience any other problems ;)
