### ISSUE TITLE
Allow memray to be usable for python under MacOS

### ISSUE THREAD

**Issue by particleman314** [bloomberg/memray#50]
## Feature Request

**Is your feature request related to a problem? Please describe.** A clear and concise description
of what the problem is. Ex. I have an issue when [...]

**Describe the solution you'd like** A clear and concise description of what you want to happen.
Add any considered drawbacks.

**Describe alternatives you've considered** A clear and concise description of any alternative
solutions or features you've considered.

**Teachability, Documentation, Adoption, Migration Strategy** If you can, explain how users will be
able to use this and possibly write out a version the docs. Maybe a screenshot or design?

Is there a timeline to allow for memray to be used by python under MacOS, I see when I try to install memray I get...
```Collecting memray
  Downloading memray-1.0.3.tar.gz (922 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 922.8/922.8 KB 2.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "/Users/klusman/Work/GIT_Projects/python-packages/BASE_SERVICES/bd_auto_detector/virtual_SIGBDAutoConfigMgr/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/klusman/Work/GIT_Projects/python-packages/BASE_SERVICES/bd_auto_detector/virtual_SIGBDAutoConfigMgr/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/klusman/Work/GIT_Projects/python-packages/BASE_SERVICES/bd_auto_detector/virtual_SIGBDAutoConfigMgr/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/d9/clqq3k317czgdkt8x8pd52dm0000gn/T/pip-build-env-98qpwlmp/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 178, in get_requires_for_build_wheel
          config_settings, requirements=['wheel'])
        File "/private/var/folders/d9/clqq3k317czgdkt8x8pd52dm0000gn/T/pip-build-env-98qpwlmp/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/d9/clqq3k317czgdkt8x8pd52dm0000gn/T/pip-build-env-98qpwlmp/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 209, in <module>
          raise RuntimeError("memray only supports Linux platforms")
      RuntimeError: memray only supports Linux platforms
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.```

**Comment by pablogsal** [comment]
As mentioned in https://github.com/bloomberg/memray/issues/22 is unlikely that we will be adding macOS support soon due to limitations on the techniques memray uses to do tracking.

You can still use memray in a docker container running in MacOS both M1 and intel.

I'm closing the issue but stay tuned as we would announce this change in the future :)

**Comment by godlygeek** [comment]
Update! We've now added macOS support to Memray, both for M1 and Intel Macs. It will be included in the Memray 1.3 release, which we are releasing today.

@pablogsal is a wizard. 😄
