### ISSUE TITLE
Native C++ trace flamegraph error

### ISSUE THREAD

**Issue by xty438307820** [bloomberg/memray#686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

when I use --native to start my program, I get the bin, I try to use memray flamegraph to convert, I get

⚠  This capture file is large and may take a long time to process  ⚠

Next time, consider using the `--aggregate` option to `memray run` to reduce the size of the file.
Check https://bloomberg.github.io/memray/run.html#aggregated-capture-files for more information.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/server_trunk_cn/lib/python3.11/site-packages/memray/__main__.py", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/server_trunk_cn/lib/python3.11/site-packages/memray/commands/__init__.py", line 138, in main
    arg_values.entrypoint(arg_values, parser)
  File "/root/server_trunk_cn/lib/python3.11/site-packages/memray/commands/common.py", line 304, in run
    self.write_report(
  File "/root/server_trunk_cn/lib/python3.11/site-packages/memray/commands/common.py", line 203, in write_report
    reporter = self.reporter_factory(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/server_trunk_cn/lib/python3.11/site-packages/memray/reporters/flamegraph.py", line 359, in from_snapshot
    return cls._from_any_snapshot(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/server_trunk_cn/lib/python3.11/site-packages/memray/reporters/flamegraph.py", line 288, in _from_any_snapshot
    tuple(record.hybrid_stack_trace())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/memray/_memray.pyx", line 351, in memray._memray.AllocationRecord.hybrid_stack_trace
  File "src/memray/_memray.pyx", line 260, in memray._memray.hybrid_stack_trace
AssertionError

what the reason? thank you

### Memray Version

1.14.0

### Python Version

3.11

### Operating System

Linux

**Comment by pablogsal** [comment]
Unfortunately without the code that you are running and a description of how to make it run we cannot do much on our side as we cannot reproduce this.

could you please give us a minimal reproducer?

**Comment by pablogsal** [comment]
Closing as without a reproducer we cannot investigate
